PACKAGE_NAME="sc200pc"
PACKAGE_VERSION="0.9.0"
BUILT_MODULE_NAME[0]="sc200pc"
DEST_MODULE_LOCATION[0]="/kernel/drivers/media/i2c"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
AUTOINSTALL="yes"
