"""Emit kernel tables of selected OuterNode::Init functions as a C header.

Reads ipu7-camera-hal's Ipu75xaStaticGraphAutogen.cpp and writes, per node,
the kernel UUIDs, the RCB and resolution-history bitmaps, and the system API
sizes, so convert-100002.cpp can map kernels between node types the same way
OuterNode::InitRunKernels lays out their data.

Usage: gen-kernel-meta.py <Ipu75xaStaticGraphAutogen.cpp> <out.h> <Node>...
"""
import re
import sys

src = open(sys.argv[1]).read()
out = ['// Generated by gen-kernel-meta.py; do not edit.', '#include <cstdint>', '']
for node in sys.argv[3:]:
    body = re.search(r'void %sOuterNode::Init\(.*?\n\}' % node, src, re.S).group(0)
    uuids = re.findall(r'(\d+) /\*\w+\*/', re.search(
        r'uint16_t kernelsUuids\[\d+\] = \{(.*?)\};', body, re.S).group(1))
    rcb = re.search(r'kernelsRcbBitmap = (0x[0-9A-Fa-f]+)', body).group(1)
    hist = re.search(r'kernelsResolutionHistoryGroupBitmap = (0x[0-9A-Fa-f]+)', body).group(1)
    sizes = re.findall(r'(\d+) /\*\w+\*/', re.search(
        r'uint8_t systemApisSizes\[\d+\] = \{(.*?)\};', body, re.S).group(1))
    assert len(uuids) == len(sizes)
    out += [
        f'struct {node}Meta {{',
        f'    static constexpr uint32_t count = {len(uuids)};',
        f'    static constexpr uint16_t uuids[{len(uuids)}] = {{{", ".join(uuids)}}};',
        f'    static constexpr uint64_t rcb = {rcb}ULL;',
        f'    static constexpr uint64_t hist = {hist}ULL;',
        f'    static constexpr uint8_t apiSizes[{len(sizes)}] = {{{", ".join(sizes)}}};',
        '};',
        '',
    ]
open(sys.argv[2], 'w').write('\n'.join(out))
